### ISSUE TITLE
community map improvements suggestiions

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/sandbox#144]
- cannot see OS Map as the polygons are covering it. Can we make them more transparent ?
-  let zoom at least a couple of extra levels to see the whole UK.

**Comment by jrajak10** [comment]
Cannot zoom any further as map returns an error and tiles do not load. I added this to the report.

**Comment by sebastianovide** [comment]
can we make it even more transparent... I still don't see any value in having a base map
